from typing import Protocol

from src.core.models import ChannelState, DigestItem, DigestQueue, User, UserChannel


class UserRepository(Protocol):
    async def get_by_telegram_id(self, telegram_user_id: int) -> User | None: ...
    async def get_or_create(self, telegram_user_id: int) -> User: ...


class UserChannelRepository(Protocol):
    async def list_for_user(self, user_id: int) -> list[UserChannel]: ...
    async def add(self, channel: UserChannel) -> UserChannel: ...
    async def remove(self, user_id: int, target: str) -> bool: ...
    async def get(self, user_id: int, channel_id: int) -> UserChannel | None: ...


class ChannelStateRepository(Protocol):
    async def get(self, user_id: int, channel_id: int) -> ChannelState | None: ...
    async def save(self, state: ChannelState) -> None: ...


class DigestQueueRepository(Protocol):
    async def create(self, queue: DigestQueue) -> DigestQueue: ...
    async def get_active(self, user_id: int) -> DigestQueue | None: ...
    async def next_unsent(self, user_id: int) -> DigestItem | None: ...
    async def mark_sent(self, item_id: int) -> None: ...
